spring.application.name=demo

# Nombre personalizado para la cookie
server.servlet.session.cookie.name=MI_SESION

# La sesión expira en 10 minutos sin actividad
server.servlet.session.timeout=10m

# JavaScript no puede leer la cookie (más seguro)
server.servlet.session.cookie.http-only=true